/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/carers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List carers (optionally filtered) */
        get: operations["getCarers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visits (optionally filtered) */
        get: operations["getVisits"];
        put?: never;
        /** Create a visit (operator only) */
        post: operations["createVisit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A single visit (scoped by role) */
        get: operations["getVisit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign or reassign a visit to a carer (operator only) */
        patch: operations["assignVisit"];
        trace?: never;
    };
    "/api/visits/{id}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Carer checks in to a visit (assigned carer or operator). */
        post: operations["checkInVisit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{id}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark a visit task done/undone (assigned carer or operator) */
        put: operations["toggleVisitTask"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{id}/check-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Carer checks out of a visit (assigned carer or operator) */
        post: operations["checkOutVisit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save the visit report (assigned carer or operator) */
        put: operations["saveVisitReport"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AI agent runs awaiting supervision (admin only) */
        get: operations["getAgentRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-runs/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or override an agent run, capturing a rationale (admin only) */
        post: operations["decideAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clients (operator only) */
        get: operations["getClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List chat messages in a channel */
        get: operations["getMessages"];
        put?: never;
        /** Post a chat message (broadcast over SSE) */
        post: operations["postMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email + password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user (from token) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat channels visible to the current user */
        get: operations["getChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "carer" | "operator" | "relative" | "admin";
        AgentRun: {
            id: string;
            agent: string;
            project: string;
            task: string;
            summary: string;
            rationale: string;
            diff: string;
            provenance: {
                skill: string;
                scope: string;
                prompt: string;
            };
            /** @enum {string} */
            status: "proposed" | "approved" | "overridden";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            decidedAt?: string;
            decisionNote?: string;
        };
        AgentRunsResponse: {
            data: components["schemas"]["AgentRun"][];
            total: number;
        };
        AgentDecisionRequest: {
            /** @enum {string} */
            decision: "approved" | "overridden";
            note?: string;
        };
        User: {
            id: string;
            name: string;
            email: string;
            role: components["schemas"]["Role"];
            carerId?: string;
            relatedClientId?: string;
        };
        LoginRequest: {
            email: string;
            password: string;
            /**
             * @description Which front-end is signing in (gates by role)
             * @enum {string}
             */
            app?: "ops" | "mobile";
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["User"];
        };
        Channel: {
            id: string;
            name: string;
        };
        ChannelsResponse: {
            data: components["schemas"]["Channel"][];
            total: number;
        };
        /** @enum {string} */
        CarerStatus: "active" | "inactive" | "onboarding";
        /** @enum {string} */
        VisitStatus: "scheduled" | "in_progress" | "completed" | "missed";
        Carer: {
            id: string;
            name: string;
            region: string;
            status: components["schemas"]["CarerStatus"];
            visitsThisWeek: number;
        };
        Visit: {
            id: string;
            clientId: string;
            client: string;
            carerId: string;
            carerName: string;
            region: string;
            /** Format: date-time */
            scheduledAt: string;
            durationMin: number;
            status: components["schemas"]["VisitStatus"];
            clientLat: number;
            clientLng: number;
            clientAddress: string;
            tasks: components["schemas"]["VisitTask"][];
            /** Format: date-time */
            checkInAt?: string;
            /** Format: date-time */
            checkOutAt?: string;
            report?: string;
        };
        Client: {
            id: string;
            name: string;
            region: string;
            lat: number;
            lng: number;
            address: string;
        };
        VisitTask: {
            id: string;
            label: string;
            done: boolean;
        };
        ClientsResponse: {
            data: components["schemas"]["Client"][];
            total: number;
        };
        AssignVisitRequest: {
            carerId: string;
        };
        VisitReportRequest: {
            report: string;
        };
        NewVisitRequest: {
            clientId: string;
            carerId: string;
            /** Format: date-time */
            scheduledAt: string;
            durationMin: number;
            tasks?: string[];
        };
        CheckInRequest: {
            lat: number;
            lng: number;
        };
        TaskToggleRequest: {
            done: boolean;
        };
        Message: {
            id: string;
            channelId: string;
            author: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        NewMessage: {
            channelId?: string;
            author?: string;
            body: string;
        };
        /** @description Payload of an SSE "alert" event (not a REST response). */
        Alert: {
            id: string;
            /** @enum {string} */
            level: "info" | "warning" | "critical";
            message: string;
            visitId: string;
            ts: number;
        };
        CarersResponse: {
            data: components["schemas"]["Carer"][];
            total: number;
        };
        VisitsResponse: {
            data: components["schemas"]["Visit"][];
            total: number;
        };
        MessagesResponse: {
            data: components["schemas"]["Message"][];
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        ts: number;
                    };
                };
            };
        };
    };
    getCarers: {
        parameters: {
            query?: {
                region?: string;
                status?: components["schemas"]["CarerStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Carers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarersResponse"];
                };
            };
        };
    };
    getVisits: {
        parameters: {
            query?: {
                status?: components["schemas"]["VisitStatus"];
                carerId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitsResponse"];
                };
            };
        };
    };
    createVisit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewVisitRequest"];
            };
        };
        responses: {
            /** @description Created visit */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVisit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignVisit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignVisitRequest"];
            };
        };
        responses: {
            /** @description Updated visit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    checkInVisit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CheckInRequest"];
            };
        };
        responses: {
            /** @description Updated visit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggleVisitTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskToggleRequest"];
            };
        };
        responses: {
            /** @description Updated visit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    checkOutVisit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated visit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveVisitReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitReportRequest"];
            };
        };
        responses: {
            /** @description Updated visit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAgentRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    decideAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentDecisionRequest"];
            };
        };
        responses: {
            /** @description Updated run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRun"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMessages: {
        parameters: {
            query?: {
                channelId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesResponse"];
                };
            };
        };
    };
    postMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewMessage"];
            };
        };
        responses: {
            /** @description Created message */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token + user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelsResponse"];
                };
            };
        };
    };
}
